version: '3'
services:
  db:
    image: postgis/postgis:12-3.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=typeorm_naming
    ports:
      - 5432:5432
